apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:woLpTKRxU0vguoFXAwv3EQ17IJ2gCv7LG2rJxCY0+f/DwkNHqFuwPDN54n3j5pQObd1HF2qwO91I5dSQPyvunzM72w5rOQlJFmqo1kNCYUYSL+GoTDHcJY1X5aV2sfoEmvIQ9qVSvvAM7cn5HmH9EUKU1MCoHu8dJ2nY9DsBxwboIhTUIqOruSEtRwWU4M1jw+db/DnX0SRPTy8CoUypXJ88MfYBno4EXGL1uCARMk0+bCFfBAaHtL4QPnG8d7B4Gask8L5wUWHrAblleotpDmFxUnsZp5x+vDl5Rn7mdJM21KRpaBdSMOBoihM=,iv:g6MqrswT87vbR1/rzjhAuRYQRe026J/YhEFLPcEUV44=,tag:NwhgtzcGdvsFKeGTTi80dg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dWRyb29acG9XRzVSbzZo
            N1BURkU2QURQM0VVbWVnQUpScGI1Z3J5ZURrCk5FelA4SVViY21NK09rV3RRRmtv
            b21BemhTaWNMa09mQUtucVNqZnlhdlUKLS0tIFlaanFIQVBGd1VoNHpxOStCd21W
            WjFMazg5cnlhKzNMbFJFalB0MXJnNEEKFQust7wl6J3vJxEtuw4druabs7FWbtp3
            xaDSY0PeLCDlFGUplmkuTnSOF2niUGYR3bN6XHA47Fn85/fvWdnFuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k7jay2vxq7dx0dqh40dy7hlhlsx2u0jn9rtxm7a9kypnhm055tsgnd989
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T05:24:19Z"
    mac: ENC[AES256_GCM,data:yt4mFcbfhdlyhjXmg6m5flgGFZWJbhXYYgTgtFbo2s0dh4QhjcH3AtNM13Ujb2vCIkTKc/xyAHNwiTqpt151dVMuTYuME82MelYFI3TkYtuTGJc6WiSuzphTktcJYICU91LO9whoQrZr74iLB5E4aSjOeOsoLpxpbMNoVsREc8M=,iv:fd6PBjJVKMOHsvIFHCFJ3iS14HW+KzbMmb6t6Jxz7sA=,tag:QiwvMQt9QHZGfVFLFtLCxw==,type:str]
    version: 3.13.2
