apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
spec:
  ingressClassName: traefik
  tls:
  - host:
    - ab.angelchavez.net
    secretName: audiobookshelf-tls-secret
  rules:
    - host: ab.angelchavez.net
      http:
        paths:
          - backend:
              service:
                name: audiobookshelf
                port:
                  number: 3005
            path: /
            pathType: Prefix

