apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 # node group ID
        runAsUser: 1000 # node user ID
        runAsGroup: 1000

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.35.1
          ports:
            - containerPort: 3005

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
 
          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /config # Where the database and settings must go
              subPath: config
            - name: audiobookshelf-data
              mountPath: /metadata # Where covers and metadata must go
              subPath: metadata
            - name: audiobookshelf-data
              mountPath: /audiobooks # A folder inside my PVC to store the audio files
              subPath: audiobooks
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc

