apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1EtsePNvllz5zH9cwda/YSexXISi4czsF4HnFCRx0nx0EOVRpEYovBEmcOU8X6HILsVcTaiSCRLwaSh6YBfflOJ51KFUOUjLwg/CyGwNpksNK3cP2h2iC/aH+NWwSWZYfeVWDcFxWFlXSZVMTZpq6oUvjkQbP/ENSqQ038fdHrHYBM7uf758pR4guYQKaqX7Et7Hbbn3X8xC6za5DZWS+z/TXomi2ceIVq2tqME59BbHleNjC15pRPU9NYGJ/det8ykHhBdgBybipjBy0m0KSGBzf6Ww75i4wEZE3LuNs+VxFXcGQgSxXJpsI7s=,iv:2P+2eQ8y+HectDcmWmgpwhioCW+Rm7weTr2KEGpffIg=,tag:Y6lUrL9NpDaPih+R+o1uYA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcWZldFZuYnoweFNlUlhU
            WmtWblNtcFlxMWFpaHN3TFNPYTlOQXBzZlM0CjA0VVNlZnJvYVFodmp3ZmdzUTJJ
            VFg3dk5KbFRvcVZGZnkxQ2ZLQW15Q0UKLS0tICtDeXI3OFZRSTZiaW8vTzVWUTFt
            MU0vS0RjbU81bUpSZkdTZmdhQnpSQlEKwRqK47IRXUbb5bUYPyMhgz/wPczQkk7m
            xcNLGQzVBW4np5VujIpGKm2HDrHk1QGHC3Ptgb5861X6WSw2moMhtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k7jay2vxq7dx0dqh40dy7hlhlsx2u0jn9rtxm7a9kypnhm055tsgnd989
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T09:12:10Z"
    mac: ENC[AES256_GCM,data:fhVAANjYQRUzTzsSAoO2B8vYp0Oc2tprZ0gXcN0ZiYVkFSTaKIhxXDDZv+/s6FjPrQn+2kQwRSkU/qA72stpSerI5H+gD2I3szwtEOnS+9WhMlju+Om249bjQNypjWPTF64xMAe9EkRzahBd1JpbrUP5cu5xOlSND82OKI2tRtg=,iv:p+6UYnzdxf+PGiVwaJnqaViBhEJiL2+yCE0fy6vVTsk=,tag:Oej71kLIIyck6HSSmHRU8w==,type:str]
    version: 3.13.2
