apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:/+t3CCEv6QgxdJKI,iv:B+H+FsX+y7f+6AokF/BZkQW9xOIAoqO7I3OSnT58c5k=,tag:bi5p/xDSgGu3bFN2ThowJw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:RdHhLMwVa02aC6GrIdkXJRoKltjXEmA3vvwtgNQ1XUc=,iv:4/AS61R7puksOYfGCeme7KOWC4kzAVPUNtXWOcpksiI=,tag:Vwg4ar0Q+csl0fd2gEEI/w==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQnF4U09xTmtjUHZxVGNP
            MmRpWmFmV3dORDZjODBRRm9QVHBRK3VzNmpBCjhwaEhyb21qOXdZbGV4TWVLbkU5
            ZVBnQTZ1VlhES2JRUmNUUjBCVFNVekEKLS0tIDJTcG91Y3IxeTl1eE5HM3lYRFNY
            SHlHQ2xXTk56bkh3ZktHbTg0VmZFT1UKFG5gZZETmnTaGIT/ew0C12k4dil4hq7c
            vVewi3MV/eDuZKD9xfPv7revdsmNAAJeqXgkklhD8KQBurr5FitSeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k7jay2vxq7dx0dqh40dy7hlhlsx2u0jn9rtxm7a9kypnhm055tsgnd989
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T09:27:11Z"
    mac: ENC[AES256_GCM,data:mr6crGsWUgvZ3C9UTjcyzloDzqMiRUnySB7N1UiXsC1iCkIQuNlGCy0eimoq9HSyPd/YnxYTRzjzzfLu+8I2LdlHjiKIvw392hk2epJiih30lCsWfeDSbZ+bA1rPGu5iRnDVDXbSsTwEsMNxyDno0HqXiA0V4B5QF/fM33dhzw4=,iv:qEJOLCU3JMRFOhiSYWJEhcZWVUY6StBWoz1Bx37DZ2g=,tag:Y6DhUeqJR1cBSKnmd8oTpg==,type:str]
    version: 3.13.2
