apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PiZhvRl7tZl+ZojELyJoWnOs32ylUmGebD3/Lw==,iv:z5yf/f+FYdV+i7Aoe66dvZQ0iRUV1CBoa1ln5C8sNOQ=,tag:p9Aan83Quf6CZ/ujh2tRqQ==,type:str]
    user: ENC[AES256_GCM,data:DaVhmB8k4yE=,iv:IplYZw/D0AftQ5WfU0VocBjTtUWWk9CVrmu+eHZDWrI=,tag:n1dwK469B/W1JIedu8Iq4w==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UlRiNnNJNnZ5Sm91SUhQ
            Z3JIek5qa05tVDJYcjU1VDlVZncxWXJzL1RvCnAvR1cyQmVkc21WaVBVUzJobnRU
            M1lzM0VheXlISHpacVFoUVhnOEFDMW8KLS0tIFU2UHlqcDl0eGpmaUU3ZnprUXdR
            NFBPR1JQQzNISHRrTlZLSjF1YittcXMK6rNttNX2Te1SHg+km+ZoGBm6mCaWQn5U
            yWKw7D8AF5+KD9U1mqGRogjA1b+HorfvcInq/LXioBB2I34XFmwb6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k7jay2vxq7dx0dqh40dy7hlhlsx2u0jn9rtxm7a9kypnhm055tsgnd989
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T05:34:08Z"
    mac: ENC[AES256_GCM,data:hx5YQLZ4QhSTJno0KuQGH9+uXwkor95qWNRepratsCXaJymHrDeslTsmLoaZeIXIBttU4ZjLw0R85DHAXW9D56QtnmASv5to3ArD1oLWVI9Mj1C6RdAQPNfW+gTxDWccoBTIpcVDawpUHQRVllvmjELecIsmTBCsL7+aah4Bq3E=,iv:AnN0/iNOw6bPlpTFSAuboixQXTQ1SOJbU8FVowSRG14=,tag:qz9QtL0bTsjkSPS5OzXl/w==,type:str]
    version: 3.13.2
