apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:GVAEysRL5QV+82TfQmjwUKQ/VH8xqglbEVkoSr66lHM=,iv:Fnd+niBiMJcMngKKma3tXCsG9sJ5eMdG4HIzagd52g4=,tag:wjvxqXA1kZJr1dg7B8qSKw==,type:str]
    admin-user: ENC[AES256_GCM,data:vOE5DZMxs94=,iv:hwchPhNGWq2CDKbj0yuG0+5P6AVcYKJJdnQrN2yOGXY=,tag:iDoMJIkfNfBJ2D0G9eGQZg==,type:str]
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVDFvOEk3UzZpUFNEM3g2
            ZnVUZWxnNDJXcXFqSWEwM2FaSldsVVNIREc0CmpHT0lGNklDeXdTa1JlcUx4WktE
            em5RcHVETWNhOXlLT2xmeUxab1M5OVkKLS0tIHB0K2QrZ2hvWUdEdjM3ZExNbEtP
            V1huRld5cU55SStsRExNR25sRnlSYlUK+KW3f2yeME551+LgZUdVIe5SAP5Ld1w/
            MSoMwsbRrc1EoCITwHgXeG9D161uMKCAomk+DqHy3GccGDmcTmf5Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k7jay2vxq7dx0dqh40dy7hlhlsx2u0jn9rtxm7a9kypnhm055tsgnd989
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T07:05:17Z"
    mac: ENC[AES256_GCM,data:/Cs9vHpFzx6V1NmN7XHPXVd1vGpkY7Cq7aMr0+cigeNPYKevqqppzx8F+o3sWcer9f9rBa0cArJDlSIqzL1zE8ehtJEIVNnBOFXpAOslRAz1sAuEfomaPjlOvHJKeTGhcn9OZCEvIjjy4/stL9Lue0OubBDIQ2r/+wxZ2/64hbg=,iv:J7xh8V3f71CGSbcezioykOx20OXfiIbcNEiTqb0AB2s=,tag:lHeUwrh3BSZEXGcZ38RNww==,type:str]
    version: 3.13.2
